### ISSUE TITLE
Add more solution status from CBC

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/rcbc#2]
Currently only optimal, unbounded and infeasible. There might be more.

**Comment by dirkschumacher** [comment]
* optimal - isProvenOptimal
* solutionlimit - isSolutionLimitReached
* nodelimit - isNodeLimitReached
* iterationlimit - isIterationLimitReached
* infeasible - isProvenInfeasible
* unbounded - isProvenDualInfeasible
* timelimit - isSecondsLimitReached
* abandoned - isAbandoned (numerical difficulties)

See here: https://www.coin-or.org/Cbc/cbcuserguide.html

**Comment by dirkschumacher** [comment]
Should there be a single status or multiple status? Maybe mimicking the api would be best? I.e. having multiple function `proven_optimal`, `proven_infeasible` etc.

**Comment by byapparov** [comment]
@dirkschumacher Should this be closed now?

**Comment by hugolarzabal** [comment]
Hello,

I post this issue here because it is related to solution status (tell me if it is better to create a new issue insteaqd)

Currently, when the solver is stopped with time limit (and probably with node, solution or iteration limit), the solver return the same status if a feasible solution has been found or not.

Would there be a way to make a new status "no_solution" when no feasible solution has been solved ?

The solver does print this information at the end of the resolution but in the link posted above, I cannot find any function to obtain it.

**Comment by rickyars** [comment]
@hugolarzabal I've submitted a pull request to return more information from the solver. It involves both changes to `ompr` and `ompr.roi`. It's still waiting to be incorporated, but now it's also behind development by a few commits. Does this do what you want?

https://github.com/dirkschumacher/ompr.roi/pull/18
https://github.com/dirkschumacher/ompr/pull/194

**Comment by hugolarzabal** [comment]
@rickyars: It is actually because I tried using your pull request that I noticed this problem (I comented it on your pull request on ompr earlier today)

ompr + ompr.roi + roi + roi.plugin.cbc + rcbc works pretty well together when using github version and your pull request.

But cbc always return a success when it is stopped by time limit even when it hasn´t encountered any feasible solution.

**Comment by rickyars** [comment]
hmm, that is weird.

i'm also having a problem with CBC that when it crashes it takes down R. i've been trying to figure that one out for over a year.

**Comment by dirkschumacher** [comment]
This is fixed now
